useNodeVersion: 24.15.0
managePackageManagerVersions: true

packages:
  - backend
  - frontend

onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  sharp: true
  unrs-resolver: true
